# Generated by Django 2.2.1 on 2019-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zhuankebaba',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=510)),
                ('post_on', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '赚客巴巴',
                'verbose_name_plural': '赚客巴巴',
                'db_table': 'zhuankebaba',
            },
        ),
    ]
