# Generated by Django 2.2.1 on 2019-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QQShare',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('create_time', models.CharField(max_length=25)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('modify_time', models.CharField(max_length=25)),
                ('owner_nick', models.CharField(max_length=255)),
                ('owner_uin', models.CharField(max_length=25)),
                ('upload_nick', models.CharField(max_length=255)),
                ('upload_uin', models.CharField(max_length=25)),
                ('filepath', models.CharField(max_length=255)),
                ('gc', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '群空间',
                'verbose_name_plural': '群空间',
                'db_table': 'qqshare',
            },
        ),
    ]
