# Generated by Django 2.2.1 on 2019-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('crawl_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '微博',
                'verbose_name_plural': '微博',
                'db_table': 'weibo',
            },
        ),
    ]
